### ISSUE TITLE
未使用関数削除

### ISSUE THREAD

**Issue by catatsuy** [catatsuy/private-isu#101]
自動でやる方法ないのかな

**Comment by edvakf** [comment]
IntelliJ 使いましょう

![cli_go_-_private-isu_-____go_src_github_com_catatsuy_private-isu_](https://cloud.githubusercontent.com/assets/28143/13853780/b4982392-ecab-11e5-8256-3a4b6a9ba715.gif)


全部シナリオ形式にしたらcli.goのやつは消しておきます。

**Comment by edvakf** [comment]
cli.goはオワタ
