### ISSUE TITLE
OSコマンドインジェクション対策

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#116]
https://github.com/catatsuy/private-isu/blob/master/webapp/ruby/app.rb#L77

**Comment by edvakf** [comment]
http://docs.ruby-lang.org/ja/2.2.0/class/Shellwords.html これかな

**Comment by catatsuy** [comment]
セキュリティ対策としてはあれですが、そもそも登録時に `/\A[0-9a-zA-Z_]{3,}\z/` 以外登録できないのでログイン時も同じチェックをすればよい？
