### ISSUE TITLE
goのエラーをそのまま競技者に見せ無い方がいい？

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#117]
こういうの `net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

本来のISUCONならベンチマーカーの言語や環境は隠蔽すべきなので、できれば隠蔽したい。

しかしそうすると我々の方で元のエラーが何かを調査するときに困る気がする。

標準エラーを別に記録するか、JSONにmessagesとは別にadmin_messagesを含めるか。

**Comment by edvakf** [comment]
#118 で標準エラーに出すようにした

**Comment by catatsuy** [comment]
ポータルサイトから見えるようにしたいと考えると、JSONの別のキーに突っ込む方がいいかと思いますが、どうですか？ @st-cyrill

**Comment by st-cyrill** [comment]
ポータルに出すならそちらの方がよいです。見せる見せないは考えてなかったです。
単にmessageに入れてもいいと思いますが、お任せさます

**Comment by catatsuy** [comment]
ポータルに出す場合は、管理画面からだけ見れるとか、そういうのを想定しています

とりあえずJSONのキーに含める方向がよさそうに思います

**Comment by catatsuy** [comment]
scoreにメッセージを入れておいて、生ログも`admin_messages`みたいなキーに入れておけば、デバッグするために `-d` を付ける必要もなくなるのでそっちの方がよさそうです

**Comment by st-cyrill** [comment]
ポータルで見られるようにするにはDBに記録しておく必要があるので、`admin_message`を追加するのがよさそう。今思えばScoreじゃなくてBenchmarkerResultみたいな名前がよかったのかも。

**Comment by st-cyrill** [comment]
Admin画面を作るならRoleをつけるといいのかな。ちょっと高機能すぎる気もする。

**Comment by edvakf** [comment]
主催者向けエラーメッセージはJSONの中にarrayで入れたほうがいいかもしれないけど、今後どうにでもなる気がするのでとりあえず何も考えずに標準エラー出力に出す方式にしたい。

というわけで今のところはベンチマーカーを実行するワーカーで標準エラー出力もキャプチャーしてDBに突っ込むのがいいと思う。
