### ISSUE TITLE
各postの個別ページを作る

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#12]
* 今のトップページでコメントするとトップページの一番上に戻ってしまうことを解消したい
  * コメント投稿欄はトップページから個別ページに移動
* ベンチマーカーがコメントしたときに、ちゃんと反映されているかチェックできる
* ここで出てるコメントの数と、トップページでCOUNTクエリで出すコメントの数があってることをベンチマーカーでチェックしたい

**Comment by edvakf** [comment]
要相談だけど、postを作るときに `POST /` じゃなくて `POST /posts` にして `POST /posts/:id` にリダイレクトさせるのはどうか。

そうするとベンチマーカー側で、タイムラインにある画像のMD5と比べるということはしなくてもよい。

**Comment by catatsuy** [comment]
> `POST /posts/:id` にリダイレクト

ではなく、`GET /posts/:id` にリダイレクト

**Comment by walf443** [comment]
よさそう

**Comment by st-cyrill** [comment]
取り急ぎ実装済み
