### ISSUE TITLE
UAにGo-http-client/1.1がまざっていることがある

### ISSUE THREAD

**Issue by walf443** [catatsuy/private-isu#125]

**Comment by catatsuy** [comment]
手抜きしているところが原因なので、 `Get` とか使っている部分を書き換えておきます

**Comment by catatsuy** [comment]
これですが、今でも送られていて、原因がGoの `net/http` の`client.go`の実装上、302リダイレクトした後に送るリクエストのUAが外から上書きされていないことが原因のようです。

`client.go` を直接書き換えると対応出来ることが分かっていますが、外から上書きできないのか調査中です。
