### ISSUE TITLE
/postsでmeを取得していない

### ISSUE THREAD

**Issue by walf443** [catatsuy/private-isu#130]
https://github.com/catatsuy/private-isu/blob/master/webapp/ruby/app.rb#L280

他の言語実装とかだとmeが必要とされたりすることがあるし、バグっちゃバグなのでmeをセットした方がよさそう

**Comment by catatsuy** [comment]
すみません。もう少し詳しくお願いします。

**Comment by walf443** [comment]
バグっている、というのは嘘か。rubyの場合はsessionを直接参照できるから渡す必要がない。
nodeはsessionが直接参照できないっぽいので、get_session_userにcsrf check用のトークンを付与して、それ経由で参照できるようにしていたのでそれで勘違いしたっぽい
