### ISSUE TITLE
post_idが数字じゃないときも通過する

### ISSUE THREAD

**Issue by walf443** [catatsuy/private-isu#132]
https://github.com/catatsuy/private-isu/blob/master/webapp/ruby/app.rb#L366

正規表現で文字列の前後\A\zまで見ていないので、abc1234とかが通過する。
DBをチェックして正しいidが確認もした方が望ましいかも。

**Comment by catatsuy** [comment]
これはただのミスですね

**Comment by catatsuy** [comment]
ちなみにGo実装だと、`strconv.Atoi` のエラーチェックをして弾いているので、この問題は発生しません。
