### ISSUE TITLE
ベンチマーカー：最初に一通りリクエストして基本的なDOMチェック等が通らなければさっさと失敗する

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#21]
基本的なチェックは厳し目に、リクエストごとのチェックは簡素にしないと性能的につらいかも？

**Comment by catatsuy** [comment]
これがE2Eテストの位置づけですか？

**Comment by edvakf** [comment]
e2eテストはコミット前にリグレッションをチェックしたり別実装を作るときにあると便利なもので、ベンチマークで使うことは想定していません。

NightmareJSではなくjsdomを使ったらベンチマーカーにも使いやすいんだろうけど。

**Comment by edvakf** [comment]
fujiwaraさんが言ってたのは、アプリケーションはキャッシュで1msで返してくるけどベンチマーカーは正直にDOMチェックしてたら絶対に1msでは終わらない、ということだった。

**Comment by edvakf** [comment]
今あるベンチマークはほとんどがきちんとDOMチェックとかまでやってるので、それらをむしろ「基本的なDOMチェック等」のほうに移動することにする。

**Comment by edvakf** [comment]
かなり大幅な構造変更をする予定

**Comment by edvakf** [comment]
https://github.com/catatsuy/private-isu/pull/82 でdone.
