### ISSUE TITLE
benchmarker 用の image がない？

### ISSUE THREAD

**Issue by keisuke-nakata** [catatsuy/private-isu#298]
おそらく同じことを言っている issue: https://github.com/catatsuy/private-isu/issues/126

benchmarker を実行すると panic します：

```
$ benchmarker -u /home/isucon/catatsuy/private-isu/benchmarker/userdata -t http://localhost
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/catatsuy/private-isu/benchmarker/util.RandomNumber(0x0)
        /home/isucon/catatsuy/private-isu/benchmarker/util/util.go:30 +0x65
main.randomImage(...)
        /home/isucon/catatsuy/private-isu/benchmarker/cli.go:234
main.(*CLI).Run(0xc0000c9f50, {0xc000080050, 0x5, 0x5})
        /home/isucon/catatsuy/private-isu/benchmarker/cli.go:118 +0x735
main.main()
        /home/isucon/catatsuy/private-isu/benchmarker/main.go:7 +0x68
```

見たところ、https://github.com/catatsuy/private-isu/blob/a505f0a75e/benchmarker/userdata.go#L63 で image を一つも取れていないことが原因のようです。
自分で画像を準備するものなのか？とも思いましたが、benchmark という性質上は事前に決められた画像セットがあるべきなのではと感じました。(実際、image 以外の [names/](https://github.com/catatsuy/private-isu/blob/a505f0a75e/benchmarker/userdata/names.txt) や [kaomoji/](https://github.com/catatsuy/private-isu/blob/a505f0a75e/benchmarker/userdata/kaomoji.txt) はダミーデータが準備されています)

実行環境：
- https://github.com/catatsuy/private-isu#ami で指定されている catatsuy_private_isu_amd64_20220529 を c4.large で起動
- https://github.com/catatsuy/private-isu を git clone
- benchmark/ 以下で `make all` し、得られた `bin/benchmarker` を `benchmarker -u /home/isucon/catatsuy/private-isu/benchmarker/userdata -t http://localhost` のように実行

**Comment by keisuke-nakata** [comment]
追記： 競技者用の AMI で benchmark を走らせようとせずに、ベンチマーク用の AMI (`catatsuy_private_isu_bench_amd64_20220529`) を使うのが正道のようです、失礼しました。

**Comment by catatsuy** [comment]
#299 で非推奨ですが競技者インスタンスでもベンチマーカーを実行できるようにしました
