### ISSUE TITLE
ベンチマーカー: 大きい画像の投稿エラーを検出できるようにする

### ISSUE THREAD

**Issue by st-cyrill** [catatsuy/private-isu#49]
#47 #48 でバリデーターがついたのでファイルサイズが10MBを超える場合にエラーにしたい

**Comment by catatsuy** [comment]
過負荷になると普通にPOSTが失敗すると思うので、そこまでチェックしなくていいかと…

それにその制限を取ったところで、アプリケーション的に問題があるとは思いません

**Comment by st-cyrill** [comment]
ベンチマーカーは大きな画像をPOSTせず、チェックしないというのもいいと思います。
そういう方針であればcloseということでお願いします。

**Comment by catatsuy** [comment]
この制限が欲しかったのは、参加者が試しに大きな画像を投稿したときにエラーになると盛り下がると思ったからです。

むしろベンチマーカーはこれ以上のサイズを送ってこないという意思表示という位置づけのイメージです。
