### ISSUE TITLE
docker compose でGo実装を選択するとアクセスできない

### ISSUE THREAD

**Issue by naoking158** [catatsuy/private-isu#520]
## 発生している現象

`docker compose up` で起動してブラウザからアクセスすると `502 Bad Gateway` が出ます。
コミット bd18a588980e08fb4eb11d2ddae4501cb7342f29 の直前までは正常に動作していました。

ログには以下エラーが出ています。

```
nginx-1      | 192.168.65.1 - - [12/Aug/2024:02:40:03 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
app-1        | 2024/08/12 02:40:03 server.go:3418: http: panic serving 172.20.0.4:48326: open templates/layout.html: no such file or directory
app-1        | goroutine 17 [running]:
app-1        | net/http.(*conn).serve.func1()
app-1        |  /usr/local/go/src/net/http/server.go:1903 +0xb0
app-1        | panic({0x3ef400?, 0x40000d3140?})
app-1        |  /usr/local/go/src/runtime/panic.go:770 +0x124
app-1        | html/template.Must(...)
app-1        |  /usr/local/go/src/html/template/template.go:368
app-1        | main.getIndex({0x4fcfc0, 0x400023e000}, 0x4000228360)
app-1        |  /src/app.go:405 +0x58c
app-1        | net/http.HandlerFunc.ServeHTTP(0x4000242000?, {0x4fcfc0?, 0x400023e000?}, 0x400021c024?)
app-1        |  /usr/local/go/src/net/http/server.go:2171 +0x38
app-1        | github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x4000076540, {0x4fcfc0, 0x400023e000}, 0x4000228360)
app-1        |  /go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x288
app-1        | net/http.HandlerFunc.ServeHTTP(0x4fdb78?, {0x4fcfc0?, 0x400023e000?}, 0x7933c0?)
app-1        |  /usr/local/go/src/net/http/server.go:2171 +0x38
app-1        | github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x4000076540, {0x4fcfc0, 0x400023e000}, 0x4000228000)
app-1        |  /go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x280
app-1        | net/http.serverHandler.ServeHTTP({0x40002100c0?}, {0x4fcfc0?, 0x400023e000?}, 0x6?)
app-1        |  /usr/local/go/src/net/http/server.go:3142 +0xbc
app-1        | net/http.(*conn).serve(0x4000214000, {0x4fdb40, 0x40001a8180})
app-1        |  /usr/local/go/src/net/http/server.go:2044 +0x508
app-1        | created by net/http.(*Server).Serve in goroutine 1
app-1        |  /usr/local/go/src/net/http/server.go:3290 +0x3f0
```

## 環境

- コミット: 682a60f1b5dd9399b13fb281d90eef50fe96913b
- OS: macOS 14.4
- docker compose version: v2.23.3-desktop.2

## 考えられる原因

コミット bd18a588980e08fb4eb11d2ddae4501cb7342f29 で multi-stage build が導入されましたが、
そのときに最終イメージに templates ディレクトリが含まれていないことが原因だと思われます。

**Comment by camrionnvmff** [comment]
あなたが提供したログを見ると、エラーメッセージはopen templates/layout.html：no such file or directoryを示しており、これは実行時に必要なテンプレートファイルが見つからないことを示しています。多段階構築を導入した後、最終的なミラーリングにテンプレートディレクトリが不足していることに言及しているため、問題の原因になる可能性があります。
﻿
この問題を解決するには、次の手順に従います。

Dockerfileをチェックするには：
Dockerfileが構築中にテンプレートディレクトリを最終ミラーに含めることを確認します。例：
#第1フェーズ構築
FROM golang:1.18 AS builder
WORKDIR /app
COPY . .
RUN go build -o myapp .

#フェーズ2構築
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/myapp .
COPY--from=builder/app/templates./templates#テンプレートディレクトリのコピーを確実にする
CMD ["./myapp"]
コードライブラリを更新するには：
問題を特定してDockerfileを修正した場合は、コードライブラリに変更を送信し、チームメンバーも最新の変更を引き出すことをお勧めします。
テスト：
Dockerfileを更新したら、ミラーを再構築してコンテナを起動し、すべてが正常に動作するようにします。次のコマンドを使用できます。
docker compose down
docker compose up --build
個人的な経験
GoアプリケーションのDockerミラーを構築していたときにも、同様のテンプレートや静的ファイルが失われる問題に遭遇したことがありました。後でservbayがdockerよりも使いやすいことに気づき、Serverbayを通じて環境を再配置しました。

**Comment by catatsuy** [comment]
refs: #522
