### ISSUE TITLE
posts.erbにまだロジックが残っている

### ISSUE THREAD

**Issue by catatsuy** [catatsuy/private-isu#57]

**Comment by edvakf** [comment]
これもらいます。 https://github.com/catatsuy/private-isu/issues/55 と合わせて諸々リファクタリングします。

**Comment by edvakf** [comment]
pとかcとか1文字変数は短い時間の中で混乱させても良くないので分かりやすい変数名にしときますね。

**Comment by edvakf** [comment]
done.
