### ISSUE TITLE
mypageの仕様を変えたい

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#60]
自分のつけたコメントと自分の写真がまぜこぜに並ぶページというのが普通のウェブアプリケーションでありえない気がする。

そういう仕様なので全件習得してsortするしかなくて微妙。

普通に自分の写真が一覧で並んでればいいような。

↑それだとISUCON的におもしろいポイントが無さそうなのが問題といえば問題かもしれないけど。

**Comment by edvakf** [comment]
ちなみにInstagramだとmypageというのは無くて、ユーザー名指定で写真一覧を表示するページがある。

そのユーザー名が自分だったら見た目がちょっと変わる感じ。

**Comment by edvakf** [comment]
`/:user_name` というページにすればインデックスきいてないクエリを増やせてチューニングポイントにはなる。

**Comment by edvakf** [comment]
mypageのままでいくなら、自分のつけたコメントと自分の写真はカラムを分けて、まぜこぜにはしないほうがいい。

全件表示させるべきかどうかは難しいところ。普通に考えて全件表示はありえないだろうけど、ページングするとエンドポイントが増えてチェックが辛い…

自分の写真についたコメント一覧カラムがあってもよさそう。

**Comment by edvakf** [comment]
@catatsuy どう思います？

**Comment by catatsuy** [comment]
チューニングポイントを増やしたくて、まぜこぜな変なページを作ったのですが、ベンチマークもしにくいし、アプリケーションとしても微妙なのでちょっと考えます

**Comment by catatsuy** [comment]
sketchと同じで `/@:account_name` というルーティングで自分の投稿と、投稿に付いたコメントを表示する、となるとチューニングポイントが少ないですかね？？

**Comment by edvakf** [comment]
それでいいと思います。

チューニングポイントは少な過ぎたら後から追加しましょう。（例えばユーザー名の横に投稿数を出すとか）

**Comment by catatsuy** [comment]
参考：[GET /@:id みたいなURLで他との衝突を避ける - Qiita](http://qiita.com/r7kamura/items/35384f6d21f23b1dcb86)

**Comment by edvakf** [comment]
やっときますー。

**Comment by edvakf** [comment]
mypageは廃止ということで。

**Comment by catatsuy** [comment]
ありがとうございます！

**Comment by catatsuy** [comment]
ベンチマーカーがまだまだ未完成なので、現時点での機能の追加・廃止のコストは低いです。どんどんやっていきましょう

**Comment by edvakf** [comment]
現時点でもmypageにリクエストしないようにすればベンチマークの開発はたぶんできるはずです。

**Comment by catatsuy** [comment]
まだそこに着手できていない…ので大丈夫です

**Comment by catatsuy** [comment]
非ログインであることの確認に `/mypage` のリダイレクトを確認していたので、どうするか考えたいです

デザインの差異とかでもいいので

**Comment by catatsuy** [comment]
`/login`とかで良さそう

**Comment by edvakf** [comment]
ログインしてると右上に自分の名前が常に出るよ。

**Comment by catatsuy** [comment]
おお なるほど
