### ISSUE TITLE
ベンチマーカー：「もっと見る」を遡っていって画像だけじゃなくページ全体を読み込んでいく

### ISSUE THREAD

**Issue by catatsuy** [catatsuy/private-isu#61]
そうしないと古いデータを全部消して高速化、という手法ができる

**Comment by edvakf** [comment]
「もっと見る」を遡っていって画像だけじゃなくページ全体を読み込んでいくworkerがいるべき。そうしないと「もっと見る」の意味が無い。

**Comment by catatsuy** [comment]
名前を変更しました

**Comment by edvakf** [comment]
`/posts/:id` と `/@:account_name` にも適当にリクエスト投げたい。

**Comment by catatsuy** [comment]
コメントもしないといけないので

* 非ログイン
  * ひたすらページをさかのぼり、画像を読み込む
* ログイン
  * ひたすらページをさかのぼり、コメントもしていく
  * コメント数は乱数でバラバラにする
  * コメント数も正しいかチェックしたい

**Comment by edvakf** [comment]
> コメント数も正しいかチェックしたい

ひたすらリクエストしていくworkerは単純にリクエストが成功するかだけを見て、チェックは甘めにした方がいいと思う。チェック厳しめのやつは別で走らせればいいので。

**Comment by edvakf** [comment]
done.
