### ISSUE TITLE
MySQLのタイムゾーン

### ISSUE THREAD

**Issue by catatsuy** [catatsuy/private-isu#78]
実際の環境を用意するときに考慮する必要がある

**Comment by catatsuy** [comment]
`my.cnf`の設定も重要

**Comment by edvakf** [comment]
https://github.com/catatsuy/private-isu/blob/master/webapp/ruby/app.rb#L39 アプリケーションではこうやってる。とりあえずよくわからないがこれしないと https://github.com/catatsuy/private-isu/commit/8b127edc6752e05b461e26430e490229aced9e99 これが動かない。
