### ISSUE TITLE
indexで「もっとみる」

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#8]
LIMIT, OFFSET方式にしたいけど、アプリケーション的にmax_id方式のほうが自然。

max_idで継ぎ足すんだけど、中でやってることは同じw という感じにするとよさそう。

**Comment by edvakf** [comment]
テンプレートで30件以上ならbreakしたりdel_flagを見て出し分けているが、気づきにくいのでコントローラー側に持ってきて良さそう。

**Comment by edvakf** [comment]
現在一番下に表示されているpostのcreated_atをmax_created_atとしてリクエスト。

サーバー側は、そのcreated_atまで含めて30件返す（HTML）

クライアント側のJSで重複を排除して継ぎ足す。

JS実装は変更してはいけないレギュレーションにする。

**Comment by st-cyrill** [comment]
TODO: クライアント側のJSで重複を排除して継ぎ足す。

そこまで厳密じゃなくてもいいと思います
