### ISSUE TITLE
アプリケーションに仕込んだ最適化ポイントにしっかり負荷をかけたい

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#85]
* ログインしまくる→外部プロセス呼び出し
* /posts/:id ページにアクセスしまくる→ `select *` で画像バイナリを取得してくる

**Comment by catatsuy** [comment]
ログインは現状でも結構な頻度で走っていると思うので、今度集まったときに各々のルーティングへのアクセス頻度について議論・検証したいです。

**Comment by edvakf** [comment]
たぶんもういいはず。
