### ISSUE TITLE
チェッカーまわりリファクタリングしたい

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#88]
https://github.com/catatsuy/private-isu/pull/83#issuecomment-195920078

## CheckFuncの中で次のリクエストをするのをやめたい

CheckFuncはそのリクエストのチェックに徹したい。

goは内部的には非同期IOだけどうまく隠蔽されててコールバックスタイルにならずにすむところが良いところのはず。一直線に書きたい。

### before

```go
	a := checker.NewAction("GET", "/")
	a.ExpectedStatusCode = http.StatusOK
	a.ExpectedLocation = "/"
	a.Description = "/にある画像にひたすらアクセス"
	a.CheckFunc = func(s *checker.Session, body io.Reader) error {
		doc, _ := goquery.NewDocumentFromReader(body)

		imgCnt := doc.Find("img").Each(func(_ int, selection *goquery.Selection) {
			url, _ := selection.Attr("src")
			imgReq := checker.NewAction("GET", url)
			imgReq.Play(s)
		}).Length()

		if imgCnt < PostsPerPage {
			return errors.New("1ページに表示される画像の数が足りません")
		}
		return nil

	}
```

### after

```go
	a := checker.NewAction("GET", "/")
	a.ExpectedStatusCode = http.StatusOK
	a.ExpectedLocation = "/"
	a.Description = "/にある画像にひたすらアクセス"

        imageUrls := []string
	a.CheckFunc = func(s *checker.Session, body io.Reader) error {
		doc, _ := goquery.NewDocumentFromReader(body)

		imgCnt := doc.Find("img").Each(func(_ int, selection *goquery.Selection) {
			url, _ := selection.Attr("src")
			imageUrls = append(imageUrls, url)
		}).Length()

		if imgCnt < PostsPerPage {
			return errors.New("1ページに表示される画像の数が足りません")
		}
		return nil
	}
	a.Play(s)

	for _, url := range imageUrls {
		imgReq := checker.NewAction("GET", url)
		imgReq.Play(s)
	}
```

この例だと複雑になってるけど、2つ目のリクエストがさらにCheckFuncを持つときにはこのほうが良い。

## `PlayWithURL` はなくせそう

CheckFuncがリダイレクト先のURLを引数に受け取るだけで良さそう

## CheckFuncがSessionを受け取る必要もなさそう

外のスコープの値を使えば良さそう。（どちらでもよい）

## PlayとCheckFuncを分けずにの第二引数にCheckFuncを渡すスタイルでいい気がする

そのほうがコードが一直線になって良さそう

## genActionがアチコチ飛ぶのがなんか気持ち悪い

genActionはすべて消して、シナリオごとに流れを一直線に書けばいい気がしてる。

その上で共通部分をくくりだす感じで。

**Comment by edvakf** [comment]
とりあえずcli.goのチェック処理を全部scenario.goにリファクタリングして移植した。

一つ一つのシナリオが上から一直線になって読みやすくはなった。しかし、同じような処理が複数箇所に書かないといけなかったのは今後のリファクタリング課題。

それよりも大きな問題は、 `PlayWithURL` のインターフェイス。

```
	_, err = postImage.PlayWithURL(s1)
	if err != nil {
		return // TODO: どういうエラーハンドリングが適切か考える
	}
```

`CheckFunc` の外でActionをエラーにすることはできないので、ここに来た時点でエラーであってもActionはエラーにならないし、競技者にもエラーが伝わらない。

やはり `PlayWithURL` は廃止して `CheckFunc` の引数にリダイレクト先URLを受け取るか、`ExpectedLocation` で正規表現や前方一致を受け付けるようにするかのどちらかにするべき。

**Comment by catatsuy** [comment]
現状の実装だと `PlayWithURL`  と `Play` の差は返り値しかないので、返り値を受け取らないなら使う必要は無いです。

`PlayWithURL` はすごくイケてないので廃止したいですが、リダイレクト先のURLを受け取る方法がないのでとりあえず作りました。

**Comment by edvakf** [comment]
ExpectedLocationを正規表現にしてPlayWithURLを廃止することにします。

**Comment by edvakf** [comment]
> PlayとCheckFuncを分けずにの第二引数にCheckFuncを渡すスタイルでいい気がする

これだけ残ってるがあとは終わった。

CheckFuncを書いた時点でチェックできてる気になってるから、Playを呼び忘れてしまう。実際2回ぐらい気づいて直した。
