### ISSUE TITLE
投稿画像のURLに拡張子があったほうがいいか考えたい

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#95]
ファイルとして置いてnginxで配信する最適化を想定してるとしたら、拡張子が無いとContent-Type付けられなくて問題になりそう。

一応Chromeはapplication/octet-straemで来ようがtext/plainで来ようがimgタグで読み込む限りは画像は表示されるみたいだけど、ベンチマーカーはContent-Typeチェックすべき？

**Comment by catatsuy** [comment]
ベンチマーカーはDOM解析するので、拡張子を付けたファイルを置いてnginxで配信させる想定でした

一般的にもそうすると思ったので、そういう動きをするように作りましたが、Content-Typeは見てないので拡張子を付けなくてもベンチマーカーは落ちないはずです

なのでチェックした方が良さそうです

**Comment by edvakf** [comment]
拡張子つけたファイルを置くけどnginxのほうで拡張子を取るということ？

それともnginxで配信するようにしたらURLに拡張子がつくようになるということ？

**Comment by catatsuy** [comment]
nginxwは一般的な設定をすれば、拡張子から適切なContent-Typeを付けて返してくれます。

**Comment by edvakf** [comment]
伝わってないなw
